### ISSUE TITLE
Sprint #2 - Tela de Histórico

### ISSUE THREAD

**Issue by emanuelsdsj** [renatoln/CES-mobile#12]
Implementar interface da tela de Histórico.

**Comment by chrystyan96** [comment]
@emanuelssj @renatoln na parte visual, vamos seguir o modelo de tela do Emile? E a questão das requisições ao banco, é com a gente também?

**Comment by renatoln** [comment]
o filtro pode ter um impacto legal nessa tela, mas acredito que por agora isso está finalizado, temos que focar nas outras features
