### ISSUE TITLE
Definir Modelo de Dados

### ISSUE THREAD

**Issue by Mecyo** [renatoln/CES-mobile#3]
Criar estrutura inicial de entidades e seus respectivos relacionamentos.

**Comment by renatoln** [comment]
Fiz uma primeira versão dessa atividade.

Está no repositório/Documentation/data

**Comment by renatoln** [comment]
usei https://my.vertabelo.com

**Comment by Mecyo** [comment]
Tá massa!
Agora nós estamos pensando em categorizar os ítens(objetos) para melhor disposição no menu, levando em consideração o tamanho das telas dos dispositivos mobile.

**Comment by Mecyo** [comment]
A princípio talvez não se faça necessário mas, a uso futuro...

**Comment by renatoln** [comment]
vamos discutir isso na sexta. para uma primeira versão, acho que está bom. Vamos focar nas outras partes que em tese está zerada.
