### ISSUE TITLE
Prototipar interface MOBILE.

### ISSUE THREAD

**Issue by Mecyo** [renatoln/CES-mobile#4]
Definir possíveis interfaces para MOBILE.

**Comment by renatoln** [comment]
- O projeto de Interface deve ser feito já em QML.
- Criei um app básico seguindo o modelo Qt Quick Controls 2 Applications.
- Cada tela deve estar em um Page.
- Fazer também uma imagem para representar o fluxograma de navegação entre as páginas

**Comment by renatoln** [comment]
veja exemplos de componentes em https://github.com/renatoln/QML-Exemplos

**Comment by chrystyan96** [comment]
Concluído por mim e @gabrielmc com uso da ferramenta Online Mockup. Realizado 6 telas até o momento, sendo elas: Login, Cadastro, Home, Reserva, Cadastro dos objetos e Contato pros administradores de cada setor.

**Comment by chrystyan96** [comment]
Concluído por mim e @gabrielmc com uso da ferramenta Online Mockup **(NÃO ESTANDO NO QML AINDA, SÓ NA PROTOTIPAGEM).** Realizado 6 telas até o momento, sendo elas: Login, Cadastro, Home, Reserva, Cadastro dos objetos e Contato pros administradores de cada setor.

**Comment by renatoln** [comment]
É preciso observar os requisitos. Algumas coisas são feitas na parte mobile, outras só no módulo web.
Além disso, onde está o que foi feito? precisa ir para dentro do repositório. No caso do modelo de dados eu utilizei uma ferramenta, indiquei no issue correspondente qual ferramenta e salvei os fontes para permitir que outra pessoa possa evoluir.

**Comment by gabrielmc** [comment]
Creio que as **ideias iniciais** para a plataforma **WEB** atende também a para estrutura **MOBILE**, ainda não joguei no repositório pois tive tempo de sentar com @chrystyan96 agora para fomentar "toda parte de requisitos" e ainda não ta concluído mas breve estarei atualizando.

**Comment by renatoln** [comment]
Vejam esse protótipo das telas do mobile que fiz
https://app.moqups.com/renatonovais@gmail.com/aAopOV7Nby/view

**Comment by renatoln** [comment]
Faltam algumas telas ainda, por exemplo: durante a solicitação, ou transferência
as telas podem e devem ser simplificadas

**Comment by gabrielmc** [comment]
Verdade professor, estou fazendo essa tela(**transferência**) e remodelando a protatipagem ja feita com as views que o Sr. criou. @emanuelssj ,  ja me pediu pra adiantar isso, antes dele dividir as telas.

**Comment by chrystyan96** [comment]
@emanuelssj @renatoln tem algum modelo padrão da tela? (cores, posicionamento dos objetos na tela, se é swipeview, etc) É bom ter um modelo padrão pra cada um fazer sua tela se diferenciar muito na parte visual dos outros.
