### ISSUE TITLE
Representação gráfica do fluxograma de navegação

### ISSUE THREAD

**Issue by Mecyo** [renatoln/CES-mobile#7]
Fazer  uma imagem que represente o fluxograma de navegação entre as páginas da aplicação.

**Comment by chrystyan96** [comment]
Concluído por mim e @gabrielmc com uso da ferramenta Online Mockup. Realizado 6 telas até o momento, sendo elas: Login, Cadastro, Home, Reserva, Cadastro dos objetos e Contato pros administradores de cada setor.

**Comment by renatoln** [comment]
onde está o fluxograma de navegação?

**Comment by gabrielmc** [comment]
Ainda não foi realizado o fluxograma, mas pelo que já foi realizado da prototipagem tem-se a noção do que deve ser feito. Pretendo reportar o mais breve possível.

**Comment by renatoln** [comment]
fecharam isso?
